### ISSUE TITLE
Episode suggestion: CSI ! 

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/tgik#165]
I've been putting together some hackable examples of DynamicStorage and CSI, largely b/c the two are easily confused.  I think it could be done in two parts

## Part 1a: DynamicStorage

- DynamicStorage in minikube is super hackable b/c of the fact that they simply use the https://github.com/kubernetes-incubator/external-storage repo, and create a `PersistentVolume` object.

## Part 1b: Dynamic storage via GlusterFS

- A good example of pre-CSI dynamic storage is the GlusterFS dynamic provisioner.  Ive been playing with it and its not too hard to get it working, also it gives you cool in container mount results, b/c you can see the gluster volume's IP address home .

## Part 2a: CSI  (raw) 

- CSI is easy to play with via the HostPath attacher, i.e. https://github.com/kubernetes-csi/drivers/tree/master/pkg/hostpath .  csc is nice b/c it allows you to use the CSI API to mount and unmount storage.  

## Part 2b: CSI on kube

- Use https://kubernetes-csi.github.io/docs/Example.html in a bare  cluster to enable dynamic CSI based provisioning  .

Happy to help put a roadmap for hacking through this, as i think there's a need for more storage tutorials for the CSI stuff, have been banging my head at it for a few days but finally have it mostly figured out :).

**Comment by joshrosso** [comment]
The process for producing an episode is [here](https://github.com/vmware-tanzu/tgik/blob/master/documentation/README.md).  All the detail for the steps below is there.

Monday or Tuesday:
* [x] Pick a topic and create/use an issue in the repo
* [ ] If applicable coordinate with an upstream project if they're interested in attending the show
* [x] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and Vykky

Before episode:
* [ ] Create HackMD page for live notes.  Start with README template in this repo
* [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV setup is good


After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)
