### ISSUE TITLE
Episode Idea: PodSecurityPolicy

### ISSUE THREAD

**Issue by jbeda** [vmware-tanzu/tgik#174]
Suggestion from Silviu in YT comment https://www.youtube.com/watch?v=0uy2V2kYl4U&lc=UgyvgfAHHtkuahf8neR4AaABAg

**Comment by marcindulak** [comment]
Covered in episode 078 https://www.youtube.com/watch?v=zErhwjPRKn8, but the episode folder is missing from https://github.com/heptio/tgik/tree/master/episodes
