### ISSUE TITLE
Episode Idea: Cluster Autoscaler

### ISSUE THREAD

**Issue by HerrmannHinz** [vmware-tanzu/tgik#193]
i know this is a tool most of the ppl know and use but it could be still very interesting to get it explained again in detail and show its full potential: 

https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler

**Comment by joshrosso** [comment]
Great topic -- i'll be picking it up this week.

The process for producing an episode is [here](https://github.com/vmware-tanzu/tgik/blob/master/documentation/README.md).  All the detail for the steps below is there.

* [x] Pick a topic and create/use an issue in the repo
* [x] If applicable coordinate with an upstream project if they're interested in attending the show
* [x] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and boschem
  * [ ] Get confirmation from boschem that she's seen the tweet and is scheduling it

Before episode:
* [ ] Create HackMD page for live notes.  Start with README template in this repo
* [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV setup is good


After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by HerrmannHinz** [comment]
nice. looking forward!

**Comment by joshrosso** [comment]
Closed with https://github.com/vmware-tanzu/tgik/pull/247/files

@jbeda / @mauilion : Can one of ya'll close this issue?
