### ISSUE TITLE
Episode Idea: Argo Events - An event-based dependency manager for Kubernetes

### ISSUE THREAD

**Issue by VaibhavPage** [vmware-tanzu/tgik#207]
https://argoproj.github.io/argo-events/

**Comment by jbeda** [comment]
I think I'm going to do this one this week!  Going to do this and CloudEvents

This'll be TGIK 111

Monday or Tuesday:
* [ ] Pick a topic and create/use an issue in the repo
* [ ] If applicable coordinate with an upstream project if they're interested in attending the show
* [ ] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and agrey
  * [ ] Get confirmation from boschem that she's seen the tweet and is scheduling it

Before episode:
* [ ] Create HackMD page for live notes.  Start with README template in this repo
* [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV setup is good


After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by VaibhavPage** [comment]
@jbeda Let me know if I can be of any help.

**Comment by jbeda** [comment]
Thanks @VaibhavPage!

Hoisting your links from email thread: 

> Few links for Argo Events:
> 
> 1. Installation - https://argoproj.github.io/argo-events/installation/
> 2. Intro - https://argoproj.github.io/argo-events/tutorials/01-introduction/
> 3. Demo - https://argoproj.github.io/argo-events/demo/notebooks/
> 4. Concepts - https://argoproj.github.io/argo-events/concepts/gateway/

**Comment by jbeda** [comment]
Hackmd: https://hackmd.io/1h7H6fvoRRSQkl_TkOM3pQ?view
