### ISSUE TITLE
Epsiode Idea: Argo CD from Intuit

### ISSUE THREAD

**Issue by stgarf** [vmware-tanzu/tgik#233]
[https://argoproj.github.io/argo-cd/](https://argoproj.github.io/argo-cd/)

[https://github.com/argoproj/argo-cd](https://github.com/argoproj/argo-cd)

**Comment by jessesuen** [comment]
I think we can dup this to https://github.com/vmware-tanzu/tgik/issues/151

**Comment by stgarf** [comment]
Closing as duplicate of #151 :)
