### ISSUE TITLE
Episode: kubectl plugins and krew

### ISSUE THREAD

**Issue by jbeda** [vmware-tanzu/tgik#285]
Monday or Tuesday:
* [x] Pick a topic and create/use an issue in the repo
* [x] If applicable coordinate with an upstream project if they're interested in attending the show
* [x] Create the graphic
* [x] Schedule on Youtube
* [x] Add scheduled episode to TGIK playlist on YT
* [x] Create short link in rebrandly
* [x] Tweet about it from your personal account
  * [x] Post tweets on internal #tgik slack channel and cc @castrojo and agrey
  * [x] Get confirmation from boschem that she's seen the tweet and is scheduling it

Before episode:
* [x] Create HackMD page for live notes.  Start with README template in this repo
* [x] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [x] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [x] Get everything tested well before episode so you can debug
* [x] Use internal slack channel to ensure that AV setup is good

After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [x] Episode directory and README from hackmd
  * [x] Any other files from the episode that might be useful
  * [x] Update playlist.md with episode
  * Feel free to self merge
* [x] Edit YT description to point to episode directory here
* [x] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by jbeda** [comment]
Links:
* https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/
* https://github.com/kubernetes-sigs/krew

**Comment by jbeda** [comment]
HackMD: https://hackmd.io/hvIv8XcGRP6-YEdpk39m_Q?edit

**Comment by ahmetb** [comment]
https://krew.sigs.k8s.io/ is our home page.

For plugin development we have a guide that doesn't talk about Krew:

- https://krew.sigs.k8s.io/docs/developer-guide/develop/plugin-development/
- https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/
- https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/

Most interesting stuff we're doing nowadays is allowing people host plugins on decentralized indexes (as opposed to `krew-index` repo we have right now); https://github.com/kubernetes-sigs/krew/issues/566

Another interesting point is that we have a fully automated plugin update model in `krew-index` where bots create PR for new plugin versions tagged + bots approve those PRs, see an example in action here: https://github.com/kubernetes-sigs/krew-index/pull/597

For more talking points PTAL https://speakerdeck.com/alp/making-kubectl-plugins-mainstream.

As a CTA I'd like to point out we have a `#krew` channel on Kubernetes Slack.

Thanks a lot for putting this together! I’ll be there live in Chat (let me know if you ever need me to join w/ audio, happy to help).

**Comment by jbeda** [comment]
Hey @ahmetb -- would love to have you join with audio but we've never gotten the tech for that nailed down.  Just need to find a day or two to muck with it at some point.  I'll let you know if we want to try.

Thanks for all the pointers!

**Comment by jeefy** [comment]
If you want to go all Thanos on your cluster: https://github.com/honk-ci/kubectl-snap

**Comment by mauilion** [comment]
closed tgik.io/118
