### ISSUE TITLE
Episode Idea: CDK8S

### ISSUE THREAD

**Issue by Matty9191** [vmware-tanzu/tgik#303]
There was a good bit of interest in CDK8S on TGIK this week:

https://github.com/awslabs/cdk8s

**Comment by jbeda** [comment]
This one is high on my list to tackle

**Comment by jbeda** [comment]
Going to tackle this this week I think.

Monday or Tuesday:
* [ ] Pick a topic and create/use an issue in the repo
* [ ] If applicable coordinate with an upstream project if they're interested in attending the show
* [ ] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and Vykky

Before episode:
* [ ] Create HackMD page for live notes.  Start with README template in this repo
* Show Coordination with Assistant 
  * [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
  * [ ] Confirm show time and AV check 
  * [ ] Last minute retweets or topic updates
  * [ ] Sync with external guest one last time if necessary
  * [ ] 
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV se tup is good

After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by jbeda** [comment]
https://studio.youtube.com/video/gSjMYDBb5Mc

cdk.io is main page.  Going to try it with typescript as that seems to be the most fully supported.

**Comment by jbeda** [comment]
HackMD: https://hackmd.io/p6fTNb4DSvalBIgpj3oS6Q
