### ISSUE TITLE
Episode Idea: Using bitnami sealed secrets

### ISSUE THREAD

**Issue by Matty9191** [vmware-tanzu/tgik#306]
It would be cool to dive into Bitnami sealed secrets in a future episode:

https://github.com/bitnami-labs/sealed-secrets

Key security, rotation and management would be cool things to play with.

**Comment by jbeda** [comment]
Hrm! I thought we did an episode on sealed secrets but I htink that may have been a live one at a kubecon.

**Comment by Matty9191** [comment]
That's definitely possible. Would still love to see a Friday TGIk episode on this topic. Super useful, especially with the Gitops movement (Argo/Flux) that is taking place.

**Comment by jbeda** [comment]
Yup! going to do it this week.

Monday or Tuesday:
* [ ] Pick a topic and create/use an issue in the repo
* [ ] If applicable coordinate with an upstream project if they're interested in attending the show
* [ ] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and Vykky
  * [ ] Get confirmation from boschem that she's seen the tweet and is scheduling it

Before episode:
* [ ] Create HackMD page for live notes.  Start with README template in this repo
* [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV setup is good


After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by Matty9191** [comment]
Can't wait! Fits right in with the Argo CD / Flux / Gitops TGIKs you did.
