### ISSUE TITLE
Missing files for #129

### ISSUE THREAD

**Issue by marcosnils** [vmware-tanzu/tgik#307]
@mauilion any chance you can upload the `kind` configurations and other related files for #129? 

Thx for all the magic you bring to the show!

**Comment by javaducky** [comment]
Hoping this was addressed by https://github.com/vmware-tanzu/tgik/pull/312 .  The kind yaml can be found using the link to "Ian and Brad's talk".

**Comment by marcosnils** [comment]
LGTM!
