### ISSUE TITLE
Telco workloads on kubernetes

### ISSUE THREAD

**Issue by opowbow** [vmware-tanzu/tgik#330]
looking at some open course projects in around telco space.....more and more telcos looking at k8s to implement cnf - we would run through what we see in the field as the ask; what tools are out there in this space..and start building a telco platform on k8s...

**Comment by opowbow** [comment]
Monday or Tuesday:
* [ ] Pick a topic and create/use an issue in the repo
* [ ] If applicable coordinate with an upstream project if they're interested in attending the show
* [ ] Create the graphic
* [ ] Schedule on Youtube
* [ ] Add scheduled episode to TGIK playlist on YT
* [ ] Create short link in rebrandly
* [ ] Tweet about it from your personal account
  * [ ] Post tweets on internal #tgik slack channel and cc @castrojo and Vykky

Before episode:
* [ ] Create HackMD page for live notes.  Start with README template in this repo
* Show Coordination with Assistant 
  * [ ] Paste HackMD URL on internal #tgik channel and cc @castrojo or other assistant
  * [ ] Assistant adds ~5-10 news items from around the web as possible "News of the Week"
  * [ ] Confirm show time and AV check 
  * [ ] Last minute retweets or topic updates
  * [ ] Sync with external guest one last time if necessary
  * [ ] 
* [ ] Get everything tested well before episode so you can debug
* [ ] Use internal slack channel to ensure that AV se tup is good

After show (ideally right away but can wait until Monday):
* Create/submit PR for this repo
  * [ ] Episode directory and README from hackmd
  * [ ] Any other files from the episode that might be useful
  * [ ] Update playlist.md with episode
  * Feel free to self merge
* [ ] Edit YT description to point to episode directory here
* [ ] OBS/OS Upgrade if applicable (Never on the day of a show)

**Comment by evankanderson** [comment]
It looks like this is https://github.com/vmware-tanzu/tgik/tree/master/episodes/139 ?

**Comment by opowbow** [comment]
yes..i shall close the issue...thanks
