### ISSUE TITLE
Adding the host's trusted certificates or /etc/docker/certs.d/ to app container automatically 

### ISSUE THREAD

**Issue by viju2008** [vmware-tanzu/tgik#335]
Currently i have 50 pods and 20 services. I have to add a trusted CA certificate internal to all these pods. Can i apply this certificate through BOSH or through kubernetes at cluster level

However in the present scenario I will have to create a configmap and add it to all the Yaml file and redeploy them

If Kubernetes pods in TKGI could directly pick from the /etc/docker/certs.d/ as they containers will be spawned by docker ultimately OR from nodes system trusted store it would be easier to do the same .

A feature of applying the Trusted certificate to all pods in cluster or to a particular namespace will be very helpful or it could pick from system or /etc/docker/certs.d/ . This will save a lot of redeployment and yaml changes

**Comment by jbeda** [comment]
Hello -- this is probably the wrong place to look for support here @viju2008.  I'd work through your VMware account reps to get the right support for TGKI.
