### ISSUE TITLE
TGIK 164 unavailable on youtube

### ISSUE THREAD

**Issue by marcindulak** [vmware-tanzu/tgik#416]
Episode added in https://github.com/vmware-tanzu/tgik/pull/413 but no video yet.
Has it been recorded?  @rikatz 

![Screenshot from 2021-09-04 09-19-28](https://user-images.githubusercontent.com/3178318/132086456-fe159b2b-2857-48f7-b0ef-c4aa304b676f.png)

**Comment by jbeda** [comment]
@jayunit100 -- don't forget to add these to the playlist.  Fixing this now.
