### ISSUE TITLE
Episode Idea: Pinniped

### ISSUE THREAD

**Issue by margocrawf** [vmware-tanzu/tgik#464]
I'm a maintainer of Pinniped and would be interested in doing an episode.
Pinniped is a federated authentication solution for Kubernetes. It provides a secure and seamless single sign-on experience to all of your clusters with support for OIDC, LDAP and Active Directory identity providers.

Links:
- https://pinniped.dev/
- https://github.com/vmware-tanzu/pinniped
- https://www.youtube.com/watch?v=OCkTnElNE9M

**Comment by LappleApple** [comment]
Scheduled for Feb 25
